# Generated by Django 4.0.3 on 2022-03-15 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_upvotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvote',
        ),
    ]
