# Generated by Django 4.0.3 on 2022-03-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_bloguser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogUser',
            new_name='Upvoter',
        ),
        migrations.RenameField(
            model_name='upvoter',
            old_name='upvoter',
            new_name='post',
        ),
    ]
