# Generated by Django 4.0.3 on 2022-03-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_username_upvoter_voter_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upvoter',
            old_name='voter_username',
            new_name='username',
        ),
    ]
