# Generated by Django 4.0.3 on 2022-03-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comment_post_alter_upvoter_post_revisions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Revisions',
            new_name='Revision',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='pub_date',
        ),
    ]
