# Generated by Django 4.0.3 on 2022-03-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_revisions_revision_remove_comment_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='revision',
            name='content',
            field=models.TextField(default='', max_length=100000),
        ),
    ]
