# Generated by Django 4.0.3 on 2022-03-15 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_comment_comment_revision_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 14, 41, 12, 768892), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', max_length=100000),
        ),
        migrations.DeleteModel(
            name='Revision',
        ),
    ]
