# Generated by Django 4.0.3 on 2022-03-17 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_comment_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upvotes',
        ),
    ]
