# Generated by Django 4.0.3 on 2022-04-01 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 22, 7, 34, 899742), verbose_name='date published'),
        ),
    ]
