# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaPenerima', models.CharField(max_length=20)),
                ('jumlahTransfer', models.CharField(max_length=20)),
            ],
        ),
    ]
